# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 6cc6ecb1-ef72-571c-8aa5-1df67798c2d7

on:
  push:
    branches:
      - patch-1
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fruoccopublic.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c8aa21da7cfc459894770d611500f95f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f46a29cede7944e394017c24a77ca4ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c8aa21da7cfc459894770d611500f95f }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '6cc6ecb1-ef72-571c-8aa5-1df67798c2d7'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2c65b5d9265147c5ba0f0f82b655e40b }}
        images: 'fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c8aa21da7cfc459894770d611500f95f }}/sample-app-aoai-chatgpt:${{ github.sha }}'